# golangci-lint configuration for qfm
# v2 format for golangci-lint v2.8.0+
#
# Strict thresholds for production code quality:
# - gocognit: 15 (enforces simpler functions)
# - gocyclo: 10 (enforces lower cyclomatic complexity)
# - funlen: 80 lines / 50 statements

version: "2"

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  show-stats: true

linters:
  enable:
    # Core linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional quality linters
    - revive
    - gosec
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - godot
    - errname
    - errorlint
    - exhaustive
    - funlen        # Function length checker (enabled for production code)
    - gocognit
    - goprintffuncname
    - lll
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - thelper
    - unconvert
    - unparam
    - whitespace
    - testpackage
    - paralleltest
    - tparallel
    - wastedassign
    - nilnil

  disable:
    - exhaustruct   # Too noisy - requires all struct fields to be set
    - varnamelen    # Conflicts with Go conventions (i, j, ok, etc.)
    - forbidigo     # We need fmt.Printf for CLI output
    - cyclop        # Redundant with gocyclo

  exclusions:
    rules:
      - linters: [all]
        path: ".*\\.pb\\.go$"
      - linters: [all]
        path: ".*_generated\\.go$"
      # Test files: exclude noisy linters (table-driven tests are naturally long)
      - linters: [gocyclo, gocognit, errcheck, dupl, gosec, goconst, testpackage, paralleltest, thelper, noctx, funlen]
        path: "_test\\.go$"
      - linters: [lll]
        source: "^//go:generate "

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)

    govet:
      enable-all: true
      disable:
        - shadow

    gocyclo:
      # Reduced from 15 to 10 (stricter) - Phase 02.3-09
      min-complexity: 10

    gocognit:
      # Reduced from 20 to 15 (stricter) - Phase 02.3-09
      min-complexity: 15

    funlen:
      # Enabled in Phase 02.3-09 with relaxed limits for production code
      # 80 lines / 50 statements balances readability with practical needs
      # Test files are excluded via exclusions.rules
      lines: 80
      statements: 50

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 3

    lll:
      line-length: 120
      tab-width: 4

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: true

    revive:
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    gosec:
      excludes:
        - G104
        - G304
      config:
        global:
          nosec: true
          audit: true

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
